services:
  db:
    image: postgres:16
    container_name: billing_db_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: billing
      POSTGRES_PASSWORD: billing
      POSTGRES_DB: billing_db
    ports:
      - "5432:5432"
    volumes:
      - billing_pgdata:/var/lib/postgresql/data

volumes:
  billing_pgdata:
